# -------------------------------------------------------------------------------------------------------- #
#                                       PlayerStats Configuration                                          #
# -------------------------------------------------------------------------------------------------------- #
config-version: 2


                                 # ------------------------------- #
                                 #            General              #
                                 # ------------------------------- #
# If true, OP players will receive a message when they join the server if the config version is outdated
outdated-config-notifications: true

# Filtering options to control which players should be included in statistic calculations
include-whitelist-only: false
exclude-banned-players: false

# To only show statistics from players that have been online in the last [x] days, set a number for x
# Leave this on 0 to include all players
number-of-days-since-last-joined: 0


                                 # ------------------------------- #
                                 #        Format & Display         #
                                 # ------------------------------- #
# If true, the stat-numbers in the top list will be aligned with dots
use-dots: true

# The maximum number of results displayed in the top list
top-list-max-size: 10

# The title above the top list (the x is translated to the list-max-size, by default 10)
top-list-title: 'Top [x]'

# The text you want displayed for a total-on-this-server statistic
# This will be put on the same line ('In total on this server: [x] animals bred', for example)
total-server-stat-title: 'Total on'
your-server-name: 'this server'


                                 # ------------------------------- #
                                 #          Color & Style          #
                                 # ------------------------------- #
# The colors below can be Chat Colors or hex codes (format: '#xxxxxx' <-- including quotation marks!)

              # -------- Styles --------- #               # -------- Chat Colors --------- #
              #                           #               #                                #
              #           bold            #               #      red          dark_red     #
              #          italic           #               #    yellow           gold       #
              #        underlined         #               #     green        dark_green    #
              #          magic            #               #     aqua          dark_aqua    #
              #       strikethrough       #               #     blue          dark_blue    #
              # ------------------------- #               #  light_purple    dark_purple   #
                                                          #     gray          dark_gray    #
                                                          #     black           white      #
top-list:                                                 # ------------------------------ #
  title: yellow
  title-style: none

  title-number: gold
  title-number-style: none

  stat-names: yellow
  stat-names-style: none

  sub-stat-names: '#FFD52B'
  sub-stat-names-style: none

  rank-numbers: gold
  rank-numbers-style: none

  player-names: green
  player-names-style: none

  stat-numbers: '#55AAFF'
  stat-numbers-style: none

  dots: dark_gray
  dots-style: none


individual-statistics:
  player-names: gold
  player-names-style: none

  stat-names: yellow
  stat-names-style: none

  sub-stat-names: '#FFD52B'
  sub-stat-names-style: none

  stat-numbers: '#ADE7FF'
  stat-numbers-style: none


total-server:
  title: gold
  title-style: none

  server-name: gold
  server-name-style: none

  stat-names: yellow
  stat-names-style: none

  sub-stat-names: '#FFD52B'
  sub-stat-names-style: none

  stat-numbers: '#ADE7FF'
  stat-numbers-style: none