# ------------------------------
#   PlayerStats Configuration
# ------------------------------

# ------ General Options -------
# Filtering options to control which players should be included in statistic calculations
include-whitelist-only: false
exclude-banned-players: false

# To only show statistics from players that have been online in the last x days, specify the number of days here
# Leave this on 0 to include all players
number-of-days-since-last-joined: 0

# ------ Format Options --------
# The maximum number of results displayed in the top list
top-list-max-size: 10

# If true, the top list will be aligned with lines of dots so that the stat numbers are all underneath each other
use-dots: true

# ------ Color Options ---------
# The colors below can be chat color names or hex codes (format: '#xxxxxx' <-- including quotation marks!)
# The style options include: bold, italic, underlined, strikethrough, and magic
individual-statistics-color:
  player-names: gold
  stat-names: yellow
  sub-stat-names: '#FFD52B'
  stat-numbers: '#ADE7FF'

individual-statistics-style:
  player-names: none
  stat-names: none
  sub-stat-names: none
  stat-numbers: none

top-list-color:
  player-names: green
  stat-names: yellow
  sub-stat-names: '#FFD52B'
  stat-numbers: '#55aaff'
  list-numbers: gold
  dots: dark_gray

top-list-style:
  player-names: none
  stat-names: none
  sub-stat-names: none
  stat-numbers: none
  list-numbers: none




