# --------------------------------
#    PlayerStats Configuration
# --------------------------------

# ----------- General ------------
# Filtering options to control which players should be included in statistic calculations
include-whitelist-only: false
exclude-banned-players: false

# To only show statistics from players that have been online in the last x days, specify the number of days here
# Leave this on 0 to include all players
number-of-days-since-last-joined: 0


# ----------- Format -------------
# The name you want displayed for a total-on-this-server statistic
your-server-name: 'this server'

# The maximum number of results displayed in the top list
top-list-max-size: 10

# If true, the top list will be aligned with lines of dots so that the stat numbers are all underneath each other
use-dots: true


# -------- Color & Style ---------
# The colors below can be chat color names or hex codes (format: '#xxxxxx' <-- including quotation marks!)
# The style options include: bold, italic, underlined, strikethrough (and for some reason I decided to also include magic)

top-list:
  title: yellow
  title-style: none

  title-number: gold
  title-number-style: none

  stat-names: yellow
  stat-names-style: none

  sub-stat-names: '#FFD52B'
  sub-stat-names-style: none

  rank-numbers: gold
  rank-numbers-style: none

  player-names: green
  player-names-style: none

  stat-numbers: '#55AAFF'
  stat-numbers-style: none

  dots: dark_gray
  dots-style: none


individual-statistics:
  player-names: gold
  player-names-style: none

  stat-names: yellow
  stat-names-style: none

  sub-stat-names: '#FFD52B'
  sub-stat-names-style: none

  stat-numbers: '#ADE7FF'
  stat-numbers-style: none


total-server:
  title: gold
  title-style: none

  server-name: '#FFB80E'
  server-name-style: none

  stat-names: yellow
  stat-names-style: none

  sub-stat-names: '#FFD52B'
  sub-stat-names-style: none

  stat-numbers: '#ADE7FF'
  stat-numbers-style: none



