# PlayerStats Configuration

# ------ General Options -------
# The maximum number of entries displayed in the top list
top-list-max-size: 10

# --- Format & Color Options ---
# --------- Format -------------
# If true, the top list will be aligned with lines of dots so that the stat numbers are all underneath each other
use-dots: true

# ---------- Color -------------
# The colors below can be chat colors or hex codes if your server supports those (Bukkit does not, Spigot and further forks do)
# Make sure to put hex codes between quotation marks! (format: '#xxxxxx')
individual-statistics:
  player-names: gold
  stat-names: yellow
  sub-stat-names: yellow
  stat-numbers: white

top-list:
  player-names: green
  stat-names: yellow
  sub-stat-names: yellow
  stat-numbers: dark_aqua
  list-numbers: gold
  dots: dark_gray

# This provides additional styling options (italic/underline/bold, and yes, even magic)
individual-statistics-style:
  player-names: none
  stat-names: none
  sub-stat-names: none
  stat-numbers: none

# Note that making the player-names bold will cause the alignment of the stat numbers to shift slightly
top-list-style:
  player-names: none
  stat-names: none
  sub-stat-names: none
  stat-numbers: none
  list-numbers: none




