# PlayerStats Configuration

# --- General Options ---


# --- Format & Color Options ---
individual-statistics:
  player-names: gold
  stat-names: yellow
  sub-stat-names: yellow
  stat-numbers: white

ranked-list:
  player-names: green
  list-title: yellow
  sub-stat-names: yellow
  stat-numbers: white
  list-numbers: gold

# If true, the statistics will be aligned so that they are all underneath each other
  use-dots: true
  dots: gray

