main: com.gmail.artemis.the.gr8.playerstats.Main
name: PlayerStats
version: 1.3
api-version: 1.18
description: adds commands to view player statistics in chat
author: Artemis_the_gr8
commands:
  statistic:
    aliases:
      - stat
      - stats
    description: general statistic command
    permission: playerstats.stat
  statisticreload:
    aliases:
      - statreload
      - statsreload
    description: reloads the config
    usage: "§a/statisticreload"
    permission: playerstats.reload
permissions:
  playerstats.stat:
    description: allows usage of /statistic
    default: true
  playerstats.reload:
    description: allows usage of /statreload
    default: op