main: com.artemis.the.gr8.playerstats.Main
name: PlayerStats
version: 2.0
api-version: 1.13
description: adds commands to view player statistics in chat
author: Artemis_the_gr8
softdepend:
  - PlaceholderAPI
commands:
  statistic:
    aliases:
      - stat
      - stats
    description: show player statistics in private chat
    permission: playerstats.stat
  statisticshare:
    aliases:
      - statshare
      - statsshare
    description: share last stat lookup in chat
    usage: "§b/statshare"
    permission: playerstats.share
  statisticreload:
    aliases:
      - statreload
      - statsreload
    description: reloads the config
    usage: "§a/statreload"
    permission: playerstats.reload
  statisticexclude:
    aliases:
      - statexclude
      - statsexclude
    description: hide this player's statistics from /stat results
    usage: "§c/statexclude"
    permission: playerstats.exclude
permissions:
  playerstats.stat:
    description: allows usage of /statistic
    default: true
  playerstats.share:
    description: allows sharing stats in chat
    default: true
  playerstats.exclude:
    description: allows usage of /statexclude
    default: op
  playerstats.reload:
    description: allows usage of /statreload
    default: op