name: Build

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build with Maven (skip tests)
        run: mvn -B -DskipTests package

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PlayerStats-artifacts
          path: |
            target/PlayerStats-*.jar
            target/*-shaded.jar
          if-no-files-found: warn
